version: "3"

services:
  backend:
    image: filaments-backend:latest
    container_name: filaments-backend
    restart: unless-stopped
    volumes:
      - /share/Container/FilmentsManagement/backend/data:/app/data
    environment:
      - PROFILES_ROOT=/app/profiles

  frontend:
    image: filaments-frontend:latest
    container_name: filaments-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
